# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class Otomoto3Item(scrapy.Item):
    Akryl_niemetalizowany = scrapy.Field()
    Bezwypadkowy = scrapy.Field()
    Body_type = scrapy.Field()
    Color = scrapy.Field()
    Country_of_origin = scrapy.Field()
    Door_count = scrapy.Field()
    Emisja_CO2 = scrapy.Field()
    Engine_capacity = scrapy.Field()
    Engine_power = scrapy.Field()
    Faktura_VAT = scrapy.Field()
    Filtr_cząstek_stałych = scrapy.Field()
    Financing_option = scrapy.Field()
    First_registration = scrapy.Field()
    Fuel_type = scrapy.Field()
    Gearbox = scrapy.Field()
    Homologacja_ciężarowa = scrapy.Field()
    Kategoria = scrapy.Field()
    Kierownica_po_praweJ_Anglik = scrapy.Field()
    Kod_Silnika = scrapy.Field()
    Kolor = scrapy.Field()
    Kraj_pochodzenia = scrapy.Field()
    Leasing = scrapy.Field()
    Leasing_concession = scrapy.Field()
    Liczba_drzwi = scrapy.Field()
    Liczba_miejsc = scrapy.Field()
    Liczba_pozostałych_rat = scrapy.Field()
    Make = scrapy.Field()
    Marka = scrapy.Field()
    Matowy = scrapy.Field()
    Metalik = scrapy.Field()
    Metallic = scrapy.Field()
    Miesięczna_rata = scrapy.Field()
    Mileage = scrapy.Field()
    Moc = scrapy.Field()
    Model = scrapy.Field()
    Możliwość_finansowania = scrapy.Field()
    Napęd = scrapy.Field()
    No_accident = scrapy.Field()
    Nr_of_seats = scrapy.Field()
    Oferta_od = scrapy.Field()
    Opłata_początkowa = scrapy.Field()
    Perłowy = scrapy.Field()
    Pierwsza_rejestracja = scrapy.Field()
    Pierwszy_właściciel = scrapy.Field()
    Pojemność_skokowa = scrapy.Field()
    Przebieg = scrapy.Field()
    Registered_in_Poland = scrapy.Field()
    Rodzaj_paliwa = scrapy.Field()
    Rok_produkcji = scrapy.Field()
    Service_record = scrapy.Field()
    Serwisowany_w_ASO = scrapy.Field()
    Skrzynia_biegów = scrapy.Field()
    Stan = scrapy.Field()
    Transmission = scrapy.Field()
    Tuning = scrapy.Field()
    Typ = scrapy.Field()
    Uszkodzony = scrapy.Field()
    VAT_free = scrapy.Field()
    VAT_marża = scrapy.Field()
    Version = scrapy.Field()
    VIN = scrapy.Field()
    Wartość_wykupu = scrapy.Field()
    Wersja = scrapy.Field()
    Year = scrapy.Field()
    Zarejestrowany_w_Polsce = scrapy.Field()



